apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: cnas
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(254) NOT NULL,
      CONSTRAINT uq_users_email UNIQUE (email)
    );
